name: Keep irccloud alive

on:
  schedule:
    - cron: '11 * * * *'
  repository_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get install python3-requests

      - uses: actions/checkout@v2

      - name: Keep irccloud alive
        env:
          IRCCLOUD_USERNAME: ${{ secrets.IRCCLOUD_USERNAME }}
          IRCCLOUD_PASSWORD: ${{ secrets.IRCCLOUD_PASSWORD }}
        run: |
          python3 irccloud.py
